apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-flg5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-flg5
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-flg5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-flg5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-flg5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bada-tenant/status-quarkus-io/statusquarkusio-flg5@sha256:744285dcff99bf2c343a5965369eeaf231e92cf90271983819b727af9ad2cc6f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
